execute @a ~ ~ ~ execute @e[name="原金",r=6] ~ ~ ~ detect ~ ~ ~1 gold_ore 0 fill ~ ~ ~1 ~ ~ ~1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="原金",r=6] ~ ~ ~ detect ~1 ~ ~1 gold_ore 0 fill ~1 ~ ~1 ~1 ~ ~1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="原金",r=6] ~ ~ ~ detect ~-1 ~ ~1 gold_ore 0 fill ~-1 ~ ~1 ~-1 ~ ~1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="原金",r=6] ~ ~ ~ detect ~1 ~ ~-1 gold_ore 0 fill ~1 ~ ~-1 ~1 ~ ~-1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="原金",r=6] ~ ~ ~ detect ~-1 ~ ~-1 gold_ore 0 fill ~-1 ~ ~-1 ~-1 ~ ~-1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="原金",r=6] ~ ~ ~ detect ~1 ~ ~ gold_ore 0 fill ~1 ~ ~ ~1 ~ ~ air 0 destroy
execute @a ~ ~ ~ execute @e[name="原金",r=6] ~ ~ ~ detect ~-1 ~ ~ gold_ore 0 fill ~-1 ~ ~ ~-1 ~ ~ air 0 destroy
execute @a ~ ~ ~ execute @e[name="原金",r=6] ~ ~ ~ detect ~ ~ ~-1 gold_ore 0 fill ~ ~ ~-1 ~ ~ ~-1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="原金",r=6] ~ ~ ~ detect ~ ~-1 ~ gold_ore 0 fill ~ ~-1 ~ ~ ~-1 ~ air 0 destroy
execute @a ~ ~ ~ execute @e[name="原金",r=6] ~ ~ ~ detect ~ ~1 ~ gold_ore 0 fill ~ ~1 ~ ~ ~1 ~ air 0 destroy