execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~ ~ ~1 redstone_ore 0 fill ~ ~ ~1 ~ ~ ~1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~1 ~ ~1 redstone_ore 0 fill ~1 ~ ~1 ~1 ~ ~1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~-1 ~ ~1 redstone_ore 0 fill ~-1 ~ ~1 ~-1 ~ ~1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~1 ~ ~-1 redstone_ore 0 fill ~1 ~ ~-1 ~1 ~ ~-1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~-1 ~ ~-1 redstone_ore 0 fill ~-1 ~ ~-1 ~-1 ~ ~-1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~1 ~ ~ redstone_ore 0 fill ~1 ~ ~ ~1 ~ ~ air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~-1 ~ ~ redstone_ore 0 fill ~-1 ~ ~ ~-1 ~ ~ air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~ ~ ~-1 redstone_ore 0 fill ~ ~ ~-1 ~ ~ ~-1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~ ~-1 ~ redstone_ore 0 fill ~ ~-1 ~ ~ ~-1 ~ air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~ ~1 ~ redstone_ore 0 fill ~ ~1 ~ ~ ~1 ~ air 0 destroy

execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~ ~ ~1 lit_redstone_ore 0 fill ~ ~ ~1 ~ ~ ~1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~1 ~ ~1 lit_redstone_ore 0 fill ~1 ~ ~1 ~1 ~ ~1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~-1 ~ ~1 lit_redstone_ore 0 fill ~-1 ~ ~1 ~-1 ~ ~1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~1 ~ ~-1 lit_redstone_ore 0 fill ~1 ~ ~-1 ~1 ~ ~-1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~-1 ~ ~-1 lit_redstone_ore 0 fill ~-1 ~ ~-1 ~-1 ~ ~-1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~1 ~ ~ lit_redstone_ore 0 fill ~1 ~ ~ ~1 ~ ~ air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~-1 ~ ~ lit_redstone_ore 0 fill ~-1 ~ ~ ~-1 ~ ~ air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~ ~ ~-1 lit_redstone_ore 0 fill ~ ~ ~-1 ~ ~ ~-1 air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~ ~-1 ~ lit_redstone_ore 0 fill ~ ~-1 ~ ~ ~-1 ~ air 0 destroy
execute @a ~ ~ ~ execute @e[name="レッドストーンの粉",r=6] ~ ~ ~ detect ~ ~1 ~ lit_redstone_ore 0 fill ~ ~1 ~ ~ ~1 ~ air 0 destroy