execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~ ~-1 ~ minecraft:redstone_ore run fill ~ ~-1 ~ ~ ~-1 ~ air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~-1 ~ ~-1 minecraft:redstone_ore run fill ~-1 ~ ~-1 ~-1 ~ ~-1 air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~-1 ~ ~ minecraft:redstone_ore run fill ~-1 ~ ~ ~-1 ~ ~ air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~-1 ~ ~1 minecraft:redstone_ore run fill ~-1 ~ ~1 ~-1 ~ ~1 air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~ ~ ~-1 minecraft:redstone_ore run fill ~ ~ ~-1 ~ ~ ~-1 air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~ ~ ~1 minecraft:redstone_ore run fill ~ ~ ~1 ~ ~ ~1 air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~1 ~ ~-1 minecraft:redstone_ore run fill ~1 ~ ~-1 ~1 ~ ~-1 air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~1 ~ ~ minecraft:redstone_ore run fill ~1 ~ ~ ~1 ~ ~ air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~1 ~ ~1 minecraft:redstone_ore run fill ~1 ~ ~1 ~1 ~ ~1 air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~ ~1 ~ minecraft:redstone_ore run fill ~ ~1 ~ ~ ~1 ~ air destroy

execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~ ~-1 ~ minecraft:lit_redstone_ore run fill ~ ~-1 ~ ~ ~-1 ~ air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~-1 ~ ~-1 minecraft:lit_redstone_ore run fill ~-1 ~ ~-1 ~-1 ~ ~-1 air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~-1 ~ ~ minecraft:lit_redstone_ore run fill ~-1 ~ ~ ~-1 ~ ~ air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~-1 ~ ~1 minecraft:lit_redstone_ore run fill ~-1 ~ ~1 ~-1 ~ ~1 air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~ ~ ~-1 minecraft:lit_redstone_ore run fill ~ ~ ~-1 ~ ~ ~-1 air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~ ~ ~1 minecraft:lit_redstone_ore run fill ~ ~ ~1 ~ ~ ~1 air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~1 ~ ~-1 minecraft:lit_redstone_ore run fill ~1 ~ ~-1 ~1 ~ ~-1 air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~1 ~ ~ minecraft:lit_redstone_ore run fill ~1 ~ ~ ~1 ~ ~ air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~1 ~ ~1 minecraft:lit_redstone_ore run fill ~1 ~ ~1 ~1 ~ ~1 air destroy
execute as @e[type=item,name="レッドストーンの粉",r=6] at @s if block ~ ~1 ~ minecraft:lit_redstone_ore run fill ~ ~1 ~ ~ ~1 ~ air destroy