execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~-1 ~ minecraft:birch_log ["pillar_axis":"y"] run fill ~ ~-1 ~ ~ ~-1 ~ air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~-1 ~ ~-1 minecraft:birch_log ["pillar_axis":"y"] run fill ~-1 ~ ~-1 ~-1 ~ ~-1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~-1 ~ ~ minecraft:birch_log ["pillar_axis":"y"] run fill ~-1 ~ ~ ~-1 ~ ~ air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~-1 ~ ~1 minecraft:birch_log ["pillar_axis":"y"] run fill ~-1 ~ ~1 ~-1 ~ ~1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~ ~-1 minecraft:birch_log ["pillar_axis":"y"] run fill ~ ~ ~-1 ~ ~ ~-1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~ ~1 minecraft:birch_log ["pillar_axis":"y"] run fill ~ ~ ~1 ~ ~ ~1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~1 ~ ~-1 minecraft:birch_log ["pillar_axis":"y"] run fill ~1 ~ ~-1 ~1 ~ ~-1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~1 ~ ~ minecraft:birch_log ["pillar_axis":"y"] run fill ~1 ~ ~ ~1 ~ ~ air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~1 ~ ~1 minecraft:birch_log ["pillar_axis":"y"] run fill ~1 ~ ~1 ~1 ~ ~1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~1 ~ minecraft:birch_log ["pillar_axis":"y"] run fill ~ ~2 ~ ~ ~1 ~ air destroy

execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~-1 ~ minecraft:birch_log ["pillar_axis":"x"] run fill ~ ~-1 ~ ~ ~-1 ~ air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~-1 ~ ~-1 minecraft:birch_log ["pillar_axis":"x"] run fill ~-1 ~ ~-1 ~-1 ~ ~-1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~-1 ~ ~ minecraft:birch_log ["pillar_axis":"x"] run fill ~-1 ~ ~ ~-1 ~ ~ air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~-1 ~ ~1 minecraft:birch_log ["pillar_axis":"x"] run fill ~-1 ~ ~1 ~-1 ~ ~1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~ ~-1 minecraft:birch_log ["pillar_axis":"x"] run fill ~ ~ ~-1 ~ ~ ~-1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~ ~1 minecraft:birch_log ["pillar_axis":"x"] run fill ~ ~ ~1 ~ ~ ~1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~1 ~ ~-1 minecraft:birch_log ["pillar_axis":"x"] run fill ~1 ~ ~-1 ~1 ~ ~-1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~1 ~ ~ minecraft:birch_log ["pillar_axis":"x"] run fill ~1 ~ ~ ~1 ~ ~ air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~1 ~ ~1 minecraft:birch_log ["pillar_axis":"x"] run fill ~1 ~ ~1 ~1 ~ ~1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~1 ~ minecraft:birch_log ["pillar_axis":"x"] run fill ~ ~2 ~ ~ ~1 ~ air destroy

execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~-1 ~ minecraft:birch_log ["pillar_axis":"z"] run fill ~ ~-1 ~ ~ ~-1 ~ air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~-1 ~ ~-1 minecraft:birch_log ["pillar_axis":"z"] run fill ~-1 ~ ~-1 ~-1 ~ ~-1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~-1 ~ ~ minecraft:birch_log ["pillar_axis":"z"] run fill ~-1 ~ ~ ~-1 ~ ~ air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~-1 ~ ~1 minecraft:birch_log ["pillar_axis":"z"] run fill ~-1 ~ ~1 ~-1 ~ ~1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~ ~-1 minecraft:birch_log ["pillar_axis":"z"] run fill ~ ~ ~-1 ~ ~ ~-1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~ ~1 minecraft:birch_log ["pillar_axis":"z"] run fill ~ ~ ~1 ~ ~ ~1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~1 ~ ~-1 minecraft:birch_log ["pillar_axis":"z"] run fill ~1 ~ ~-1 ~1 ~ ~-1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~1 ~ ~ minecraft:birch_log ["pillar_axis":"z"] run fill ~1 ~ ~ ~1 ~ ~ air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~1 ~ ~1 minecraft:birch_log ["pillar_axis":"z"] run fill ~1 ~ ~1 ~1 ~ ~1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~1 ~ minecraft:birch_log ["pillar_axis":"z"] run fill ~ ~2 ~ ~ ~1 ~ air destroy

execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~ ~1 minecraft:leaves ["old_leaf_type":"birch"] run fill ~ ~ ~1 ~ ~ ~1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~1 ~ ~1 minecraft:leaves ["old_leaf_type":"birch"] run fill ~1 ~ ~1 ~1 ~ ~1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~-1 ~ ~1 minecraft:leaves ["old_leaf_type":"birch"] run fill ~-1 ~ ~1 ~-1 ~ ~1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~1 ~ ~-1 minecraft:leaves ["old_leaf_type":"birch"] run fill ~1 ~ ~-1 ~1 ~ ~-1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~-1 ~ ~-1 minecraft:leaves ["old_leaf_type":"birch"] run fill ~-1 ~ ~-1 ~-1 ~ ~-1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~1 ~ ~ minecraft:leaves ["old_leaf_type":"birch"] run fill ~1 ~ ~ ~1 ~ ~ air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~-1 ~ ~ minecraft:leaves ["old_leaf_type":"birch"] run fill ~-1 ~ ~ ~-1 ~ ~ air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~ ~-1 minecraft:leaves ["old_leaf_type":"birch"] run fill ~ ~ ~-1 ~ ~ ~-1 air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~-1 ~ minecraft:leaves ["old_leaf_type":"birch"] run fill ~ ~-1 ~ ~ ~-1 ~ air destroy
execute as @e[type=item,name="シラカバの原木",r=12] at @s if block ~ ~1 ~ minecraft:leaves ["old_leaf_type":"birch"] run fill ~ ~2 ~ ~ ~1 ~ air destroy