execute as @e[type=item,name="鉄の原石",r=6] at @s if block ~ ~-1 ~ minecraft:deepslate_iron_ore run fill ~ ~-1 ~ ~ ~-1 ~ air destroy
execute as @e[type=item,name="鉄の原石",r=6] at @s if block ~-1 ~ ~-1 minecraft:deepslate_iron_ore run fill ~-1 ~ ~-1 ~-1 ~ ~-1 air destroy
execute as @e[type=item,name="鉄の原石",r=6] at @s if block ~-1 ~ ~ minecraft:deepslate_iron_ore run fill ~-1 ~ ~ ~-1 ~ ~ air destroy
execute as @e[type=item,name="鉄の原石",r=6] at @s if block ~-1 ~ ~1 minecraft:deepslate_iron_ore run fill ~-1 ~ ~1 ~-1 ~ ~1 air destroy
execute as @e[type=item,name="鉄の原石",r=6] at @s if block ~ ~ ~-1 minecraft:deepslate_iron_ore run fill ~ ~ ~-1 ~ ~ ~-1 air destroy
execute as @e[type=item,name="鉄の原石",r=6] at @s if block ~ ~ ~1 minecraft:deepslate_iron_ore run fill ~ ~ ~1 ~ ~ ~1 air destroy
execute as @e[type=item,name="鉄の原石",r=6] at @s if block ~1 ~ ~-1 minecraft:deepslate_iron_ore run fill ~1 ~ ~-1 ~1 ~ ~-1 air destroy
execute as @e[type=item,name="鉄の原石",r=6] at @s if block ~1 ~ ~ minecraft:deepslate_iron_ore run fill ~1 ~ ~ ~1 ~ ~ air destroy
execute as @e[type=item,name="鉄の原石",r=6] at @s if block ~1 ~ ~1 minecraft:deepslate_iron_ore run fill ~1 ~ ~1 ~1 ~ ~1 air destroy
execute as @e[type=item,name="鉄の原石",r=6] at @s if block ~ ~1 ~ minecraft:deepslate_iron_ore run fill ~ ~1 ~ ~ ~1 ~ air destroy